#!/usr/bin/env bash

# https://macarthur.me/posts/deploying-code-with-a-git-hook

if [ -z "$PROJECT_DIR" ]; then
  echo "PROJECT_DIR is required."
elif [ ! -d "$PROJECT_DIR/.git" ]; then
  echo ".git directory in project directory is required."
else
  echo "Updating git remotes from local environement config..."
  echo ""

  source "$PROJECT_DIR/.env"
  source "$PROJECT_DIR/.env.local"

  if [ -z "$ORIGIN_REPO" ]; then
    echo "ORIGIN_REPO is required to setup git repo remotes."
  else
    echo "Current remotes:"
    echo ""

    git remote -v

    echo ""
    echo "ORIGIN_REPO: $ORIGIN_REPO"
    echo "DEPLOYMENT_REPO_DEV: $DEPLOYMENT_REPO_DEV"
    echo "DEPLOYMENT_REPO_PROD_01: $DEPLOYMENT_REPO_PROD_01"
    echo "DEPLOYMENT_REPO_PROD_02: $DEPLOYMENT_REPO_PROD_02"
    echo "DEPLOYMENT_REPO_PROD_03: $DEPLOYMENT_REPO_PROD_03"
    echo "DEPLOYMENT_REPO_PROD_04: $DEPLOYMENT_REPO_PROD_04"
    echo "DEPLOYMENT_REPO_PROD_05: $DEPLOYMENT_REPO_PROD_05"
    echo ""

    echo "Removing current remotes... Continue (y/n)?"

    read ANSWER

    if [[ "$ANSWER" =~ ^[Yy]$ ]]; then
      echo "Removing..."

      git remote remove origin

      echo "git remote add origin \"$ORIGIN_REPO\""

      echo "Adding..."

      git remote add origin "$ORIGIN_REPO"
      git remote set-url --add --push origin "$ORIGIN_REPO" # Re-add this

      if [ -n "$DEPLOYMENT_REPO_DEV" ]; then
        echo "Adding "$DEPLOYMENT_REPO_DEV" remote..."

        git remote set-url --add --push origin "$DEPLOYMENT_REPO_DEV"
      fi

      if [ -n "$DEPLOYMENT_REPO_PROD_01" ]; then
        echo "Adding "$DEPLOYMENT_REPO_PROD_01" remote..."

        git remote set-url --add --push origin "$DEPLOYMENT_REPO_PROD_01"
      fi

      if [ -n "$DEPLOYMENT_REPO_PROD_02" ]; then
        echo "Adding "$DEPLOYMENT_REPO_PROD_02" remote..."

        git remote set-url --add --push origin "$DEPLOYMENT_REPO_PROD_02"
      fi

      if [ -n "$DEPLOYMENT_REPO_PROD_03" ]; then
        echo "Adding "$DEPLOYMENT_REPO_PROD_03" remote..."

        git remote set-url --add --push origin "$DEPLOYMENT_REPO_PROD_03"
      fi

      if [ -n "$DEPLOYMENT_REPO_PROD_04" ]; then
        echo "Adding "$DEPLOYMENT_REPO_PROD_04" remote..."

        git remote set-url --add --push origin "$DEPLOYMENT_REPO_PROD_04"
      fi

      if [ -n "$DEPLOYMENT_REPO_PROD_05" ]; then
        echo "Adding "$DEPLOYMENT_REPO_PROD_05" remote..."

        git remote set-url --add --push origin "$DEPLOYMENT_REPO_PROD_0"
      fi

      git push --set-upstream origin master

      echo ""
      echo "Remotes after update:"
      echo ""

      git remote -v

      echo ""
      echo "Server repository configured for deployment."
      echo ""
    fi
  fi
fi
