#!/usr/bin/env bash

# https://www.digitalocean.com/community/tutorials/how-to-create-a-self-signed-ssl-certificate-for-apache-in-ubuntu-18-04
# https://www.digitalocean.com/community/tutorials/how-to-secure-apache-with-let-s-encrypt-on-ubuntu-18-04
# https://www.digitalocean.com/community/tutorials/how-to-install-the-apache-web-server-on-ubuntu-18-04#step-5-%E2%80%94-setting-up-virtual-hosts-recommended

if [ -z "$WEB_HOSTNAME" ] || [ -z "$APP_ENV" ]; then
  echo "WEB_HOSTNAME and APP_ENV are required."
elif [ "$APP_ENV" != "prod" ] && [ "$APP_ENV" != "dev" ]; then
  echo "Certificates may only be installed into a remote prod or dev environment."
elif [ ! -f "/.dockerenv" ]; then
  echo ""
  echo "Web Hostname: $WEB_HOSTNAME"
  echo ""
  echo "Run the Install Certificate server command within a container. Use the"
  echo "following command to access the container cli:"
  echo ""
  echo "    $ /app/server use-app"
  echo "    $ /docker/server/install-certificate"
  echo ""
else
  echo ""
  echo "This will install a security certificate for the following web hostname:"
  echo ""
  echo "    $WEB_HOSTNAME"
  echo ""
  echo " ### Using container shell"
  echo ""
  echo "    $ WEB_HOSTNAME=[current-project-hostname]"
  echo "    $ APP_ENV=prod"
  echo "    $ export WEB_HOSTNAME"
  echo "    $ export APP_ENV"
  echo "    $ /app/docker/install-certificate"
  echo ""
  echo " ### Answering questions:"
  echo ""
  echo "    1. Enter email address: support@dialogs.com"
  echo "    2. Terms of service (A)gree/(C)ancel: a"
  echo "    3. Share email (Y)es/(N): n"
  echo "    4. HTTPS force redirect (1 no/2 yes): 1"
  echo ""

  certbot --apache -d "$WEB_HOSTNAME"

  service apache2 restart

  echo ""
  echo "Certificate installation complete."
  echo ""
fi
