#!/usr/bin/env bash

if [ -z "$PROJECT_DIR" ] || [ -z "$DEPLOY_ENV" ]; then
  echo "PROJECT_DIR and DEPLOY_ENV are required."
else
  if [ "$DEPLOY_ENV" == "local" ]; then
    "$PROJECT_DIR/server" install-local
  else
    "$PROJECT_DIR/server" install-prod
  fi
fi
