#!/usr/bin/env bash

if [ -z "$PROJECT_DIR" ] || [ -z "$DOCKER_DIR" ]; then
  echo "PROJECT_DIR and DOCKER_DIR are required."
elif [ -z "$DEPLOY_ENV" ] || [ "$DEPLOY_ENV" == "local" ]; then
  echo "Running PROD configuraiton in non-PROD deployment environment is discouraged."
else
  source "$PROJECT_DIR/.env"
  source "$PROJECT_DIR/.env.prod"

  if [ -z "$PROJECT_VOLUME" ]; then
    echo "PROJECT_VOLUME is required."
  else
    echo "Owning by site user $SITE_USER..."
    echo ""

    chown -R www-data "/mnt/$PROJECT_VOLUME"
    chgrp -R www-data "/mnt/$PROJECT_VOLUME"

    chown -R root "/mnt/$PROJECT_VOLUME/logs"
    chgrp -R root "/mnt/$PROJECT_VOLUME/logs"

    echo "Done."
  fi
fi
