#!/usr/bin/env bash

if [ -z "$PROJECT_DIR" ] || [ -z "$DEPLOY_ENV" ]; then
  echo "PROJECT_DIR and DEPLOY_ENV are required."
else
  if [ "$DEPLOY_ENV" != local ]; then
    echo "Database cannot be setup in non-local deployment environment."
  else
    if [ ! -n "$(docker inspect -f '{{.State.Running}}' "$PROJECT_KEY-data")" ]; then
      source "$PROJECT_DIR/server" start
    fi

    SETUP_DATABASE="/docker/server/setup-database"

    if [ -f "$PROJECT_DIR/docker/scripts/setup-database" ]; then
      SETUP_DATABASE="/docker/scripts/setup-database"
    fi

    docker-compose -f "$PROJECT_DIR/compose-local.yaml" --env-file "$PROJECT_DIR/.env" exec data "$SETUP_DATABASE"
  fi
fi
