#!/usr/bin/env bash

if [ -z "$PROJECT_DIR" ] || [ -z "$DOCKER_DIR" ]; then
  echo "PROJECT_DIR and DOCKER_DIR are required."
elif [ -z "$APP_ENV" ] || [ "$APP_ENV" != "prod" ]; then
  echo "Running PROD configuraiton in DEV is discouraged."
else
  echo "Starting production server."
  echo ""

  source "$PROJECT_DIR/.env"
  source "$PROJECT_DIR/.env.prod"

  APP_ENV=prod

  export APP_ENV
  export PROJECT_KEY
  export PROJECT_VOLUME

  export PROD_DB_HOST
  export PROD_DB_PORT
  export PROD_DB_NAME
  export PROD_DB_USER
  export PROD_DB_PASSWORD

  echo "Stopping any running server containers..."
  echo ""

  time "$PROJECT_DIR/server" stop-prod

  echo ""
  echo "Starting server...."
  echo ""

  RUN_COMMAND="docker-compose -f $PROJECT_DIR/compose-prod.yaml up -d --remove-orphans;"

  if [ $(whoami) != "$SITE_USER" ]; then
    echo "su'ing $SITE_USER..."
    echo ""

    time su -c "cd $PROJECT_DIR ; source $PROJECT_DIR/.env ; docker-compose -f $PROJECT_DIR/compose-prod.yaml up -d --remove-orphans" -m - "$SITE_USER"
  else
    echo "Running as $SITE_USER..."
    echo ""

    time eval "$RUN_COMMAND"
  fi

  echo ""
  echo "Server started in background. Use './server stop-prod' to quit."
fi
