#!/usr/bin/env bash

if [ -z "$PROJECT_DIR" ]; then
  echo "PROJECT_DIR is required."
else
  ENV_FILE="$PROJECT_DIR/.env"
  COMPOSE_FILE="compose-local.yaml"

  source "$ENV_FILE"

  if [ "prod" == "$APP_ENV" ]; then
    COMPOSE_FILE="compose-prod.yaml"

    source "$PROJECT_DIR/.env.prod"

    export PROD_DB_HOST
    export PROD_DB_PORT
    export PROD_DB_NAME
    export PROD_DB_USER
    export PROD_DB_PASSWORD
  fi

  docker-compose -f "$COMPOSE_FILE" ps
fi
