#!/usr/bin/env bash

if [ -z "$PROJECT_DIR" ] || [ -z "$DEPLOY_ENV" ]; then
  echo "PROJECT_DIR and DEPLOY_ENV are required."
else
  if [ "$DEPLOY_ENV" == "local" ]; then
    time "$PROJECT_DIR/server" stop-local
  else
    time "$PROJECT_DIR/server" stop-prod
  fi
fi
