#!/usr/bin/env bash

if [ -z "$PROJECT_DIR" ]; then
  echo "PROJECT_DIR is required."
else
  echo "Running shell within cache container..."
  echo ""

  COMPOSE_FILE="compose-local.yaml"

  source "$PROJECT_DIR/.env"

  if [ "$DEPLOY_ENV" == "local" ]; then
    source "$PROJECT_DIR/.env.local"
    source "$PROJECT_DIR/.env.prod"

    docker-compose -f "$COMPOSE_FILE" exec cache redis-cli
  else
    COMPOSE_FILE="compose-prod.yaml"

    PROJECT_DIR="$REPO_DIR"

    if ! command -v redli &> /dev/null; then
      cd /tmp
      wget https://github.com/IBM-Cloud/redli/releases/download/v0.5.2/redli_0.5.2_linux_amd64.tar.gz
      tar xvf redli_0.5.2_linux_amd64.tar.gz
      sudo mv redli /usr/local/bin/
      rm redli_0.5.2_linux_amd64.tar.gz
    fi

    redli -u "$(dirname $REDIS_URL)"
  fi
fi
