version: '3.8'

services:
  
  app:
    container_name: "${PROJECT_KEY}-app"
    build: .
    restart: always
    ports:
      - "${WEB_PORT}:80"
    env_file:
      - .env
      - .env.local
    environment:
      WORDPRESS_CONFIG_EXTRA: "file_exists(ABSPATH . 'wp-content/env.php') && require_once ABSPATH . 'wp-content/env.php';"
    volumes:
      - ./docker:/docker:cached
      - ./web:/var/www/html:cached
      - ./logs:/var/log
  
  data:
    container_name: "${PROJECT_KEY}-data"
    image: mysql:8
    restart: always
    env_file:
      - .env
      - .env.local
      - .env.prod
    volumes:
      - ./docker:/docker:cached
      - ./docker/data:/var/lib/mysql

#  cli:
#    container_name: ${PROJECT_KEY}_cli
#    image: wordpress:cli
#    build:
#      context: .
#      dockerfile: Dockerfile-cli
#    env_file:
#      - .env
#      - .env.local
#    volumes:
#      - ./docker:/docker:cached
#      - ./web:/var/www/html:cached
#      - ./logs:/var/log

volumes:
  web:
  docker:
  logs:
  data:
