version: '3.8'

services:
  
  app:
    container_name: "${PROJECT_KEY}-app"
    build: .
    restart: always
    ports:
      - "${WEB_PORT}:80"
    extra_hosts:
      - "${WEB_HOSTNAME}:127.0.0.1"
    ulimits:
      nofile: 131072
      memlock: 82000
    env_file:
      - .env
      - .env.local
    environment:
      WORDPRESS_CONFIG_EXTRA: "file_exists(ABSPATH . 'wp-content/env.php') && require_once ABSPATH . 'wp-content/env.php';"
    volumes:
      - ./docker:/docker:cached
      - ./web:/var/www/html:cached
      - ./docker/etc/varnish:/etc/varnish:cached
      - ./logs:/var/log
  
  data:
    container_name: "${PROJECT_KEY}-data"
    image: mysql:8
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    cap_add:
      - SYS_NICE
    env_file:
      - .env
      - .env.local
      - .env.prod
    volumes:
      - ./docker:/docker:cached
      - ./docker/data/mysql:/var/lib/mysql

  cache:
    container_name: "${PROJECT_KEY}-cache"
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes:
      - ./docker/data/redis:/data

volumes:
  web:
  docker:
  logs:
  data:
  cache:
