version: '3.1'

services:
  
  app:
    container_name: "${PROJECT_KEY}-app"
    build: "${REPO_DIR}"
    restart: always
    ports:
      - 80:80
      - 443:443
    extra_hosts:
      - "${WEB_HOSTNAME}:127.0.0.1"
    ulimits:
      nofile: 131072
      memlock: 82000
    env_file:
      - .env
      - .env.prod
    environment:
      WORDPRESS_DB_HOST: "${PROD_DB_HOST}:${PROD_DB_PORT}"
      WORDPRESS_DB_NAME: "${PROD_DB_NAME}"
      WORDPRESS_DB_USER: "${PROD_DB_USER}"
      WORDPRESS_DB_PASSWORD: "${PROD_DB_PASSWORD}"
      WORDPRESS_CONFIG_EXTRA: "file_exists(ABSPATH . 'wp-content/env.php') && require_once ABSPATH . 'wp-content/env.php';"
    volumes:
      - ./web:/var/www/html
      - ./docker:/docker
      - "/mnt/${PROJECT_VOLUME}/uploads:/var/www/html/wp-content/uploads"
      - "/mnt/${PROJECT_VOLUME}/conf/apache:/etc/apache2"
      - "/mnt/${PROJECT_VOLUME}/conf/letsencrypt:/etc/letsencrypt"
      - "/mnt/${PROJECT_VOLUME}/conf/varnish:/etc/varnish"
      - "/mnt/${PROJECT_VOLUME}/logs:/var/log"

volumes:
  web:
  mnt:
