version: '3.1'

services:
  
  app:
    image: wordpress
    restart: always
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: "${PROD_DB_HOST}:${PROD_DB_PORT}"
      WORDPRESS_DB_NAME: "${PROD_DB_NAME}"
      WORDPRESS_DB_USER: "${PROD_DB_USER}"
      WORDPRESS_DB_PASSWORD: "${PROD_DB_PASSWORD}"
    volumes:
      - ./web/wp-content:/var/www/html/wp-content
      - ./logs:/var/log

volumes:
  web:
