version: '3.8'

services:
  
  app:
    container_name: "${PROJECT_KEY}-app"
    build: .
    restart: always
    ports:
      - "${WEB_PORT}:80"
    env_file:
      - .env
      - .env.local
    volumes:
      - ./docker:/docker:cached
      - ./web/wp-content:/var/www/html/wp-content:cached
      - ./logs:/var/log
  
  data:
    container_name: "${PROJECT_KEY}-data"
    image: mysql:5.7
    restart: always
    env_file:
      - .env
      - .env.local
      - .env.prod
    volumes:
      - ./docker:/docker:cached
      - ./docker/data:/var/lib/mysql

volumes:
  web:
  docker:
  logs:
  data:
