#!/usr/bin/env bash

function cwd {
  echo "$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
}

export -f cwd

export CWD=$(cwd)
export PROJECT_DIR="$CWD"
export DOCKER_DIR="$PROJECT_DIR/docker"

echo "$PWD"
echo "$CWD"
echo "$PROJECT_DIR"
echo "$DOCKER_DIR"
echo ""
