#!/usr/bin/env bash

function cwd {
  echo "$( cd "$(dirname "${BASH_SOURCE[0]}")" > /dev/null 2>&1 && pwd)"
}

export -f cwd

function has_command {
  COMMAND=$1

  if [ -n "$(printf '%s\n' "${COMMANDS[@]}" | grep -e "^$COMMAND$")" ]; then
    echo true
  fi

  if [ "prod" != "$APP_ENV" ] && [ -n "$(printf '%s\n' "${DEV_COMMANDS[@]}" | grep -e "^$COMMAND$")" ]; then
    echo true
  fi

  if [ "prod" == "$APP_ENV" ] && [ -n "$(printf '%s\n' "${PROD_COMMANDS[@]}" | grep -e "^$COMMAND$")" ]; then
    echo true
  fi
}

if [ -n "$PROJECT_DIR" ]; then
  HEADLESS=true
else
  HEADLESS=false
fi

if [[ "$HEADLESS" = false ]]; then
  SECTION="~~~~~~~~~~~~~~~~~~~~~~~~~~~"

  echo ""
  echo "Welcome to the Server Dock!"
  echo $SECTION
  echo ""
fi

export CWD="$(cwd)"
export PROJECT_DIR="$CWD"
export DOCKER_DIR="$PROJECT_DIR/docker"
export COMMANDS=(help status tail)
export DEV_COMMANDS=(start restart open-site open-admin stop use-app use-data use-client status tail container-logs setup install uninstall config-repo)
export PROD_COMMANDS=(start-prod stop-prod open-site open-admin use-app use-client su-prod status tail container-logs init-prod own-volume install-site-user setup-volume deploy)

COMMAND=$1

if [ ! -n "$COMMAND" ]; then
  COMMAND=help
fi

if [ -f "$PROJECT_DIR/.env" ]; then
  source "$PROJECT_DIR/.env"
fi

if [ -n "$(has_command $COMMAND)" ]; then
  if [ "help" != "$COMMAND" ]; then
    echo "COMMAND: $COMMAND"
    echo ""

    COMMAND_SCRIPT="$DOCKER_DIR/$COMMAND-server"

    if [ -f "$COMMAND_SCRIPT" ]; then
      source "$COMMAND_SCRIPT"
    else
      echo "Command not found!"
    fi
  else
    echo "COMMOM { ${COMMANDS[@]}"
    echo "DEV    { ${DEV_COMMANDS[@]}"
    echo "PROD   { ${PROD_COMMANDS[@]}"
  fi
fi

if [ "$HEADLESS" = false ]; then
  echo ""
  echo $SECTION
  echo ""
fi
