#!/bin/bash

source ../.env

GIT_DIR="/${PROJECT_NAME}-${APP_ENV^^}"

TARGET="/${GIT_DIR}-run"

while read oldrev newrev ref
do
  BRANCH="$(git rev-parse --symbolic --abbrev-ref $ref)"

  echo "Push received! Deploying branch: ${BRANCH}..."

  git --work-tree=$TARGET --git-dir=$GIT_DIR checkout -f $BRANCH
done
