#!/usr/bin/env bash

echo "Enabling and starting crontab."

systemctl enable cron
service cron start

VHOST_CONF="/etc/apache2/sites-enabled/000-default.conf"
PORTS_CONF="/etc/apache2/ports.conf"
VARNISH_DIR="/etc/varnish"

systemctl enable varnish

if [ "$HTTP_ACCELERATION" == yes ]; then
  echo "Starting HTTP acceleration."

  sed -i -e 's/<VirtualHost \*:80>/<VirtualHost *:8080>/' "$VHOST_CONF"

  if ! grep -q "8080" "$PORTS_CONF"; then
    sed -i -e 's/80/8080/' "$PORTS_CONF"
  fi

  if [ ! -e "$VARNISH_DIR/secret" ]; then
    uuidgen > "$VARNISH_DIR/secret"
    chgrp www-data "$VARNISH_DIR/secret"
  fi

  service varnish start

  nohup varnishlog -a -w /var/log/varnish/varnish50x.log -q "RespStatus >= 500 or BerespStatus >= 500"
  nohup varnishlog -a -A -w /var/log/varnish/apache50x.log -q "RespStatus >= 500 or BerespStatus >= 500"
else
  echo "Disabling HTTP acceleration."

  sed -i -e 's/<VirtualHost \*:8080>/<VirtualHost *:80>/' "$VHOST_CONF"
  sed -i -e 's/:8080/:80/' "$PORTS_CONF"
fi

echo ""
echo "Starting web server."
echo ""

/usr/local/bin/docker-entrypoint.sh apache2-foreground
