#!/usr/bin/env bash

if [ -z "$PROJECT_DIR" ] || [ -z "$DEPLOY_ENV" ]; then
  echo "PROJECT_DIR and DEPLOY_ENV are required."
else
  COMPOSE="$PROJECT_DIR/compose-local.yaml"

  if [ "$DEPLOY_ENV" != "local" ]; then
    COMPOSE="$PROJECT_DIR/compose-prod.yaml"
  fi

  docker-compose -f "$COMPOSE" build

  echo ""
  echo "Container rebuilt, use ./server restart to use new container."
  echo ""
fi
