#!/usr/bin/env bash

function make_project_env_file {
  FILENAME="$PROJECT_DIR/.env"

  echo "Generate Project Environment Variables"
  echo "====="
  echo ""

  echo "What is the project name (alphanumeric, dashes and periods only)?"

  read PROJECT_KEY

  echo "What is the project site username (e.g., dmag)?"

  read SITE_USER

  echo "What is the current application environment (dev, test, prod)?"

  read APP_ENV

  echo "What is the current deployment environment (local, dev, prod)?"

  read DEPLOY_ENV

  echo "What is the web protocol of the current environment (http or https)?"

  read WEB_PROTOCOL

  echo "What is the hostname of the current environment (e.g. localhost or macbook-pro.local equivalent)?"

  read WEB_HOSTNAME

  echo "What is the web port to use (generally ~9000)?"

  read WEB_PORT

  echo ""

  BASE_URL="$WEB_PROTOCOL://$WEB_HOSTNAME"

  if [ "$WEB_PORT" != "80" ] && [ "$WEB_PORT" != "8080" ]; then
    BASE_URL="$BASE_URL:$WEB_PORT"
  fi

  echo "Using BASE_URL of $BASE_URL."
  echo ""

  echo "Writing $FILENAME"

  echo "PROJECT_KEY=$PROJECT_KEY" > $FILENAME
  echo ""
  echo "APP_ENV=PROD" >>$FILENAME
  echo "DEPLOY_ENV=$DEPLOY_ENV" >>$FILENAME
  echo "" >> $FILENAME
  echo "WEB_PROTOCOL=$WEB_PROTOCOL" >> $FILENAME
  echo "WEB_HOSTNAME=$WEB_HOSTNAME" >> $FILENAME
  echo "WEB_PORT=$WEB_PORT" >> $FILENAME
  echo "BASE_URL=$BASE_URL" >> $FILENAME
  echo "" >> $FILENAME
  echo "MYSQL_RANDOM_ROOT_PASSWORD='1'" >> $FILENAME
}

function make_local_env_file {
  FILENAME="$PROJECT_DIR/.env.local"

  echo "Generate Local Environment Variables"
  echo "====="
  echo ""

  echo "What is the project's remote repository url (git@...)?"

  read ORIGIN_REPO

  echo "What is the project's PROD remote deployment url (root@[IP or domain])?"

  read DEPLOYMENT_REPO_PROD

  echo "What is the project's DEV remote deployment url (root@[IP or domain])?"

  read DEPLOYMENT_REPO_DEV

  echo "What is the local database name (alphanumeric and underscores)?"

  read MYSQL_DATABASE

  echo "What is the local database user?"

  read MYSQL_USER

  echo "What is the local database user password?"

  read MYSQL_PASSWORD

  echo ""
  echo "Writing $FILENAME"

  echo "# This part is needed for MySQL to create the user successfully on first touch." > $FILENAME
  echo "MYSQL_DATABASE=$MYSQL_DATABASE" >> $FILENAME
  echo "MYSQL_USER=$MYSQL_USER" >> $FILENAME
  echo "MYSQL_PASSWORD=$MYSQL_PASSWORD" >> $FILENAME
  echo "" >> $FILENAME
  echo "ORIGIN_REPO=$ORIGIN_REPO" >> $FILENAME
  echo "DEPLOYMENT_REPO_PROD=$DEPLOYMENT_REPO_PROD" >> $FILENAME
  echo "DEPLOYMENT_REPO_DEV=$DEPLOYMENT_REPO_DEV" >> $FILENAME
  echo "" >> $FILENAME
  echo "# These are the actual settings for the Wordpress docker installation." >> $FILENAME
  echo "WORDPRESS_DB_HOST=$PROJECT_KEY-data" >> $FILENAME
  echo "WORDPRESS_DB_NAME=$MYSQL_DATABASE" >> $FILENAME
  echo "WORDPRESS_DB_USER=$MYSQL_USER" >> $FILENAME
  echo "WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD" >> $FILENAME
}

function make_prod_env_file {
  FILENAME="$PROJECT_DIR/.env.prod"

  echo "Generate Production Environment Variables"
  echo "====="
  echo ""

  echo "What is the production database host?"

  read PROD_DB_HOST

  echo "What is the production database port?"

  read PROD_DB_PORT

  echo "What is the production database name (alphanumeric and underscores)?"

  read PROD_DB_NAME

  echo "What is the production database user?"

  read PROD_DB_USER

  echo "What is the production database user password?"

  read PROD_DB_PASSWORD

  echo ""

  echo "PROD_DB_HOST=$PROD_DB_HOST" > $FILENAME
  echo "PROD_DB_PORT=$PROD_DB_PORT" >> $FILENAME
  echo "PROD_DB_NAME=$PROD_DB_NAME" >> $FILENAME
  echo "PROD_DB_USER=$PROD_DB_USER" >> $FILENAME
  echo "PROD_DB_PASSWORD=$PROD_DB_PASSWORD" >> $FILENAME
}

function make_project_directories {
  WP_CONTENT="$PROJECT_DIR/wp-content"
  WP_CONTENT_PLUGINS="$WP_CONTENT/plugins"
  WP_CONTENT_THEMES="$WP_CONTENT/themes"

  if [ ! -d "$WP_CONTENT" ]; then
    mkdir "$WP_CONTENT"
  fi

  if [ ! -d "$WP_CONTENT_PLUGINS" ]; then
    mkdir "$WP_CONTENT_PLUGINS"
  fi

  if [ ! -d "$WP_CONTENT_THEMES" ]; then
    mkdir "$WP_CONTENT_THEMES"
  fi
}

if [ -z "$PROJECT_DIR" ] || [ -z "$DOCKER_DIR" ]; then
  echo "PROJECT_DIR and DOCKER_DIR are required."
else
  make_project_env_file

  source "$PROJECT_DIR/.env" && echo ""

  make_local_env_file

  source "$PROJECT_DIR/.env.local" && echo ""

  make_prod_env_file

  touch "$DOCKER_DIR/.installed"

  echo $(date '+%Y-%m-%d %H:%M:%S') >> "$DOCKER_DIR/.installed"

  echo "Done."
fi
