#!/usr/bin/env bash

if [ -z "$PROJECT_DIR" ] || [ -z "$DOCKER_DIR" ]; then
  echo "PROJECT_DIR and $DOCKER_DIR is required."
else
  echo "Installing deployment hooks..."
  echo ""

  RELAY_DIR="/deploy-relay"
  POST_RECEIVE_FILENAME="$RELAY_DIR/hooks/post-receive"

  source "$PROJECT_DIR/.env"

  echo "Path: $DOCKER_DIR/.githooks/post-receive"
  echo "Link: $POST_RECEIVE_FILENAME"

  if [ ! -d "$RELAY_DIR" ]; then
    git init --bare $RELAY_DIR
  fi

  if [ -d "$PROJECT_DIR/.git" ]; then
    echo "Removing $PROJECT_DIR/.git directory..."

    rm -r "$PROJECT_DIR/.git"

    echo "Removed."
    echo ""
  fi

  if [ -L "$POST_RECEIVE_FILENAME" ]; then
    echo ""
    echo "Deleting previous symlink $POST_RECEIVE_FILENAME..."

    rm "$POST_RECEIVE_FILENAME"

    echo "Removed."
  fi

  echo "Making synlink for automated deployment..."

  ln -s "$DOCKER_DIR/.githooks/post-receive" "$POST_RECEIVE_FILENAME"

  chown -R www-data /deploy-relay
  chgrp -R www-data /deploy-relay
  chgrp -R www-data /deploy-repo
  chown -R www-data /deploy-repo

  echo ""
  echo "Done."
fi
