#!/usr/bin/env bash

if [ -z "$PROJECT_DIR" ] || [ -z "$DOCKER_DIR" ]; then
  echo "PROJECT_DIR and $DOCKER_DIR is required."
else
  echo "Installing deployment hooks..."
  echo ""

  RELAY_DIR="$(dirname $PROJECT_DIR)/deploy-relay"
  POST_RECEIVE_FILENAME="$RELAY_DIR/hooks/post-receive"

  if [ ! -d "$RELAY_DIR" ]; then
    git init --bare $RELAY_DIR
  fi

  if [ ! -f "$POST_RECEIVE_FILENAME" ]; then
    source "$PROJECT_DIR/.env"

    echo "Path: $DOCKER_DIR/.githooks/post-receive"

    ln -s "$DOCKER_DIR/.githooks/post-receive" $POST_RECEIVE_FILENAME
  fi

  echo ""
  echo "Done."
fi
