#!/usr/bin/env bash

if [ "root" != "$(whoami)" ]; then
  echo "Installation script must be run as root."
else
  PROJECT_DIR="/deploy-repo"
  RELAY_DIR="/deploy-relay"
  DOCKER_DIR="$PROJECT_DIR/docker"

  DEPLOY_ENV=prod
  SITE_USER=dmag

  export PROJECT_DIR
  export RELAY_DIR
  export DOCKER_DIR
  export DEPLOY_ENV
  export SITE_USER

  bash <(wget -qO - https://raw.githubusercontent.com/jfdialogs/wp-standard-server/master/docker/install-site-user)

  echo ""

  HAS_SITE_USER="$(getent passwd $SITE_USER)"

  if [ -z "$HAS_SITE_USER" ]; then
    echo "Installation failed on missing site user $SITE_USER."
  else
    echo "What is the git repo ssh address (format: git@github:[org]/[project-name].git)?"

    read GIT_REPO

    echo ""

    if [ -z "$GIT_REPO" ]; then
      echo "Install canceled."
    else
      if [ -d "$PROJECT_DIR" ]; then
        rm -d "$PROJECT_DIR"
      fi

      if [ -d "$RELAY_DIR" ]; then
        rm -d "$RELAY_DIR"
      fi

      mkdir -m 777 "$PROJECT_DIR"
      mkdir -m 777 "$RELAY_DIR"

      chown -R "$SITE_USER" "$PROJECT_DIR"
      chown -R "$SITE_USER" "$RELAY_DIR"
      chgrp -R "$SITE_USER" "$PROJECT_DIR"
      chgrp -R "$SITE_USER" "$RELAY_DIR"

      echo "Git cloing $GIT_REPO into $PROJECT_DIR as $SITE_USER"
      echo ""

      su -c "git clone $GIT_REPO $PROJECT_DIR" - "$SITE_USER"

      echo ""

      if [ ! -s "$PROJECT_DIR/server" ]; then
        echo "Git repo $GIT_REPO not found or install error."
        echo ""
      else
        "$DOCKER_DIR/own-project"

        INSTALL_STEP[1]="$DOCKER_DIR/install-deployment-hooks"
        INSTALL_STEP[2]="$DOCKER_DIR/init-prod-server"
        INSTALL_STEP[3]="$DOCKER_DIR/own-volume"
        INSTALL_STEP[4]="$DOCKER_DIR/setup-volume"

        STEPS="$(printf '%s;\n' ${INSTALL_STEP[@]})"

        echo "Performing steps as $SITE_USER:"
        echo ""
        echo "$(printf '  - %s;\n' ${INSTALL_STEP[@]})"
        echo ""

        # Run all install steps as dmag user
        su -c "$STEPS" - "$SITE_USER"
      fi

      echo "Production server installed."
    fi
  fi
fi
