#!/usr/bin/env bash

# See https://unix.stackexchange.com/a/210232

function make_site_user {
  SITE_USER_HOME="/home/$SITE_USER"
  SITE_USER_SSH_DIR="$SITE_USER_HOME/.ssh"
  SITE_USER_RSA_PRIV_KEY="$SITE_USER_SSH_DIR/id_rsa"
  SITE_USER_RSA_PUB_KEY="$SITE_USER_RSA_PRIV_KEY.pub"

  KNOWH_HOSTS="$SITE_USER_SSH_DIR/known_hosts"
  AUTHORIZED_KEYS="$SITE_USER_SSH_DIR/authorized_keys"

  useradd -m -d "$SITE_USER_HOME" -s /bin/bash "$SITE_USER"

  mkdir "$SITE_USER_SSH_DIR"
  touch "$AUTHORIZED_KEYS"

  ssh-keygen -t rsa -f "$SITE_USER_RSA_PRIV_KEY" -P "" -C "support@dialogs.com"

  eval $(ssh-agent -s)
  ssh-add "$SITE_USER_RSA_PRIV_KEY"

  chown -R "$SITE_USER:$SITE_USER" "$SITE_USER_SSH_DIR"
  chmod 700 "$SITE_USER_SSH_DIR"
  chmod 600 "$SITE_USER_SSH_DIR/known_hosts"
  chmod 600 "$SITE_USER_SSH_DIR/authorized_keys"
  chmod go-w "$SITE_USER_HOME"

  usermod -aG www-data "$SITE_USER"
  usermod -aG docker "$SITE_USER"
  usermod -aG sudo "$SITE_USER"

  echo "$SITE_USER ALL=(ALL:ALL) NOPASSWD: ALL" | sudo tee "/etc/sudoers.d/$SITE_USER"

  echo "Copy and paste the following $SITE_USER public key into the project's"
  echo "Github repository Deploy Keys config:"
  echo ""

  cat "$SITE_USER_RSA_PUB_KEY"

  echo ""
  echo "Hit ENTER to continue."

  read NOTHING

  touch "$KNOWN_HOSTS"

  GITHUB_KEY_HOST="github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=="
  GITHUB_KEY_IPS[0]="140.82.114.3 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=="
  GITHUB_KEY_IPS[1]="140.82.112.3 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=="
  GITHUB_KEY_IPS[2]="140.82.112.4 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=="
  GITHUB_KEY_IPS[3]="140.82.113.3 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=="
  GITHUB_KEY_IPS[4]="140.82.113.4 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=="
  GITHUB_KEY_IPS[5]="140.82.114.4 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=="

  echo "$GITHUB_KEY_HOST" >> "$KNOWN_HOSTS"

  for GITHUB_KEY_IP in "${GITHUB_KEY_IPS[@]}"
  do
      echo "$GITHUB_KEY_IP" >> "$KNOWN_HOSTS"
  done

  service sshd restart
}

if [ -z "$PROJECT_DIR" ] || [ -z "$DOCKER_DIR" ]; then
  echo "PROJECT_DIR and DOCKER_DIR are required."
else
  if [ -z "$SITE_USER" ] && [ ! -f "$PROJECT_DIR/.env" ]; then
    echo "Missing SITE_USER and no .env file."
  else
    if [ -z "$SITE_USER" ]; then
      source "$PROJECT_DIR/.env"
      source "$PROJECT_DIR/.env.prod"
    fi

    HAS_SITE_USER="$(getent passwd $SITE_USER)"

    if [ -n "$HAS_SITE_USER" ]; then
      echo "User $SITE_USER already exists, skipping."
      echo ""
    else
      echo "Making home and auth keys for site user $SITE_USER..."
      echo ""

      make_site_user

      HAS_SITE_USER="$(getent passwd $SITE_USER)"

      if [ -z "$HAS_SITE_USER" ]; then
        echo "Error, user $SITE_USER not installed."
      else
        echo "Site user $SITE_USER successfully installed."
      fi
    fi
  fi
fi
