#!/usr/bin/env bash

# See https://unix.stackexchange.com/a/210232

function make_site_user {
  SITE_USER_HOME="/home/$SITE_USER"
  SITE_USER_SSH_DIR="$SITE_USER_HOME/.ssh"
  SITE_USER_RSA_PRIV_KEY="$SITE_USER_SSH_DIR/id_rsa"
  SITE_USER_RSA_PUB_KEY="$SITE_USER_RSA_PRIV_KEY.pub"

  useradd -m -d "$SITE_USER_HOME" -s /bin/bash "$SITE_USER"

  mkdir "$SITE_USER_SSH_DIR"
  touch "$SITE_USER_SSH_DIR/authorized_keys"

  ssh-keygen -t rsa -f "$SITE_USER_RSA_PRIV_KEY" -P "" -C "support@dialogs.com"

  eval $(ssh-agent -s)
  ssh-add "$SITE_USER_RSA_PRIV_KEY"

  chown -R "$SITE_USER:$SITE_USER" "$SITE_USER_SSH_DIR"
  chmod 700 "$SITE_USER_SSH_DIR"
  chmod 600 "$SITE_USER_SSH_DIR/authorized_keys"
  chmod go-w "$SITE_USER_HOME"

  usermod -aG www-data "$SITE_USER"
  usermod -aG docker "$SITE_USER"
  usermod -aG sudo "$SITE_USER"

  echo "$SITE_USER ALL=(ALL:ALL) NOPASSWD: ALL" | sudo tee "/etc/sudoers.d/$SITE_USER"

  echo "Copy and paste the following $SITE_USER public key into the project's"
  echo "Github repository Deploy Keys config:"
  echo ""

  cat "$SITE_USER_RSA_PUB_KEY"

  echo ""
  echo "Hit ENTER to continue."

  read NOTHING

  service sshd restart
}

if [ -z "$PROJECT_DIR" ] || [ -z "$DOCKER_DIR" ]; then
  echo "PROJECT_DIR and DOCKER_DIR are required."
else
  if [ -z "$SITE_USER" ] && [ ! -f "$PROJECT_DIR/.env" ]; then
    echo "Missing SITE_USER and no .env file."
  else
    if [ -z "$SITE_USER" ]; then
      source "$PROJECT_DIR/.env"
      source "$PROJECT_DIR/.env.prod"
    fi

    if getent passwd "$SITE_USER" > /dev/null 2>&1; then
      echo "User $SITE_USER already exists, skipping."
      echo ""
    else
      echo "Making home and auth keys for site user $SITE_USER..."
      echo ""

      make_site_user

      echo ""
    fi
  fi

  echo "Done."
fi
