#!/usr/bin/env bash

if [ "root" != "$(whoami)" ]; then
  echo "Installation script must be run as root."
else
  PROJECT_DIR="/deploy-repo"
  RELAY_DIR="/deploy-relay"
  DOCKER_DIR="$PROJECT_DIR/docker"

  DEPLOY_ENV=prod
  SITE_USER=dmag

  "$DOCKER_DIR/install-site-user"

  HAS_SITE_USER="$(getent passwd $SITE_USER)"

  if [ -z "$HAS_SITE_USER" ]; then
    echo "Installation failed on missing site user $SITE_USER."
  else
    echo "What is the git repo ssh address (format: git@github:[org]/[project-name].git)?"

    read GIT_REPO

    if [ -z "$GIT_REPO" ]; then
      echo "Install canceled."
    else
      export PROJECT_DIR
      export DOCKER_DIR
      export RELAY_DIR
      export SITE_USER
      export GIT_REPO

      git clone "$GIT_REPO" "$PROJECT_DIR"

      if [ ! -s "$PROJECT_DIR/server" ]; then
        echo "Git repo $GIT_REPO not found."
      else
        "$DOCKER_DIR/own-project"

        INSTALL_STEP[1]="$DOCKER_DIR/install-deployment-hooks"
        INSTALL_STEP[2]="$DOCKER_DIR/init-prod-server"
        INSTALL_STEP[2]="$DOCKER_DIR/own-volume"
        INSTALL_STEP[2]="$DOCKER_DIR/setup-volume"

        STEPS="$(printf '%s;\n' ${INSTALL_STEP[@]})"

        echo "Performing steps as $SITE_USER:"
        echo ""
        echo "$(printf '  - %s;\n' ${INSTALL_STEP[@]})"
        echo ""

        # Run all install steps as dmag user
        su -c "$STEPS" - "$SITE_USER"
      fi
    fi
  fi
fi
