#!/usr/bin/env bash

if [ -z "$PROJECT_DIR" ] || [ -z "$RELAY_DIR" ]; then
  echo "PROJECT_DIR and RELAY_DIR are required."
elif [ -z "$DEPLOY_ENV" ] || [ "$DEPLOY_ENV" != "prod" ]; then
  echo "Running PROD configuraiton when not in PROD is discouraged."
else
  source "$PROJECT_DIR/.env"
  source "$PROJECT_DIR/.env.prod"

  echo "Owning project directories by site user $SITE_USER..."
  echo ""

  chown -R www-data "$PROJECT_DIR"
  chgrp -R www-data "$PROJECT_DIR"
  chmod -R 777 "$PROJECT_DIR"

  chown -R www-data "$RELAY_DIR"
  chgrp -R www-data "$RELAY_DIR"
  chmod -R 777 "$RELAY_DIR"

  echo "Done."
  fi
fi
