#!/usr/bin/env bash

if [ -z "$PROJECT_DIR" ] || [ -z "$DEPLOY_ENV" ]; then
  echo "PROJECT_DIR and DEPLOY_ENV are required."
else
  if [ "$DEPLOY_ENV" == "local" ]; then
    PREVENT_WEB_OPEN=true

    export PREVENT_WEB_OPEN

    ./server start
  else
    ./server start-prod
  fi
fi
