#!/usr/bin/env bash

if [ -z "$PROJECT_DIR" ] || [ -z "$DOCKER_DIR" ]; then
  echo "PROJECT_DIR and DOCKER_DIR are required."
else
  echo "Starting local project server."
  echo ""

  if [ ! -f "$DOCKER_DIR/.installed" ]; then
    echo "Install not detected, prompting for environment installation."
    echo ""

    source "$DOCKER_DIR/install-environment"

    echo ""
    echo "Environment variables installed. Use ./server setup to pull PROD data into local database."
    echo ""
  fi

  source "$PROJECT_DIR/.env"

  echo "Stopping any running server containers..."

  source "$DOCKER_DIR/stop-server"

  echo "Starting server...."
  echo ""

  docker-compose -f "$PROJECT_DIR/compose-local.yaml" --env-file "$PROJECT_DIR/.env" up -d --remove-orphans

  echo ""
  echo "Server started in background. Waiting for availability (may take longer on first run)..."
  echo ""

  sleep 5

  WEB_URL="http://$HOSTNAME.local:$WEB_PORT"

  echo "Opening $WEB_URL..."
  echo ""

  open $WEB_URL

  echo "Done. Use './server stop' to quit."
fi
