#!/usr/bin/env bash

if [ -n "$PROJECT_DIR" ] && [ -n "$DOCKER_DIR" ]; then
  echo "Starting local project server."
    echo ""

  if [ ! -f "$DOCKER_DIR/.installed" ]; then
    echo "Install not detected, prompting for environment installation."
    echo ""

    source "$DOCKER_DIR/install-environment"

    echo ""
    echo "Environment variables installed. Pull database from PROD (y/n)?"
    echo "Note, this requires the .env.prod connection information to be available."

    read PULL_PROD_DATA

    echo ""

    if [ "$PULL_PROD_DATA" != "${PULL_PROD_DATA#[Yy]}" ]; then
      source "$DOCKER_DIR/setup-server"
    fi
  fi

  source "$PROJECT_DIR/.env"

  echo "Stopping any running server containers..."

  source "$DOCKER_DIR/stop-server"

  echo "Starting server...."
  echo ""

  docker-compose -f "$PROJECT_DIR/docker-compose.yaml" --env-file "$PROJECT_DIR/.env" up -d --remove-orphans

  echo ""
  echo "Server started in background. Waiting for availability..."
  echo ""

  sleep 5

  WEB_URL="http://$HOSTNAME.local:$WEB_PORT"

  echo "Opening $WEB_URL..."
  echo ""

  open $WEB_URL

  echo "Done. Use server stop to quit."
else
  echo "PROJECT_DIR and DOCKER_DIR are required."
fi
