#!/usr/bin/env bash

if [ -z "$PROJECT_DIR" ] || [ -z "$DOCKER_DIR" ]; then
  echo "PROJECT_DIR and DOCKER_DIR are required."
elif [ -z "$APP_ENV" ] || [ "$APP_ENV" != "prod" ]; then
  echo "Running PROD configuraiton in DEV is discouraged."
else
  echo "Starting production server."
  echo ""

  source "$PROJECT_DIR/.env"
  source "$PROJECT_DIR/.env.prod"

  export PROD_DB_HOST
  export PROD_DB_PORT
  export PROD_DB_NAME
  export PROD_DB_USER
  export PROD_DB_PASSWORD

  echo "Stopping any running server containers..."

  source "$DOCKER_DIR/stop-prod-server"

  echo "Starting server...."
  echo ""

  APP_ENV=prod

  export APP_ENV

  docker-compose -f "$PROJECT_DIR/compose-prod.yaml" up -d --remove-orphans

  echo ""
  echo "Server started in background. Use './server stop-prod' to quit."
fi
