#!/usr/bin/env bash

if [ -z "$PROJECT_DIR" ] || [ -z "$DOCKER_DIR" ]; then
  echo "PROJECT_DIR and DOCKER_DIR are required."
else
  echo "Stopping container..."
  echo ""

  source "$PROJECT_DIR/.env"
  source "$PROJECT_DIR/.env.prod"

  export PROJECT_KEY
  export PROD_DB_HOST
  export PROD_DB_PORT
  export PROD_DB_NAME
  export PROD_DB_USER
  export PROD_DB_PASSWORD

  docker-compose -f "$PROJECT_DIR/compose-prod.yaml" stop

  echo ""
  echo "Stopped."
fi
