#!/usr/bin/env bash

if [ -z "$PROJECT_DIR" ] || [ -z "$DOCKER_DIR" ]; then
  echo "PROJECT_DIR and DOCKER_DIR are required."
else
  echo "Stopping container..."
  echo ""

  if [ -f "$ENV_FILE" ]; then
    docker-compose -f "$PROJECT_DIR/compose-prod.yaml"  stop

    echo ""
    echo "Stopped."
  else
    echo "Environment file $ENV_FILE missing. Aborting."
  fi
fi
