#!/usr/bin/env bash

if [ -z "$PROJECT_DIR" ] || [ -z "$DOCKER_DIR" ]; then
  echo "PROJECT_DIR and DOCKER_DIR are required."
else
  source "$PROJECT_DIR/.env"

  echo "Logging in as su $SITE_USER..."
  echo ""

  su - "$SITE_USER"
fi
