#!/usr/bin/env bash

if [ -z "$PROJECT_DIR" ]; then
  echo "PROJECT_DIR is required."
else
  ENV_FILE="$PROJECT_DIR/.env"
  COMPOSE_FILE="compose-local.yaml"

  if [ "prod" == "$APP_ENV" ]; then
    COMPOSE_FILE="compose-prod.yaml"
  fi

  docker-compose -f "$COMPOSE_FILE" logs --follow app
fi
