#!/usr/bin/env bash

if [ -n "$PROJECT_DIR" ] && [ -n "$DOCKER_DIR" ]; then
  echo "Running shell within web app container..."
  echo ""

  ENV_FILE="$PROJECT_DIR/.env"

  if [ -f "$ENV_FILE" ]; then
    docker-compose -f "$PROJECT_DIR/compose-local.yaml" --env-file "$ENV_FILE" exec app bash
  else
    echo "Environment file $ENV_FILE missing. Aborting."
  fi
else
  echo "PROJECT_DIR and DOCKER_DIR are required."
fi
