#!/usr/bin/env bash

if [ -z "$PROJECT_DIR" ] || [ -z "$DOCKER_DIR" ]; then
  echo "PROJECT_DIR is required."
else
  echo "Running shell within web app container..."
  echo ""

  ENV_FILE="$PROJECT_DIR/.env"
  COMPOSE_FILE="compose-local.yaml"

  if [ "prod" == "$APP_ENV" ]; then
    COMPOSE_FILE="compose-prod.yaml"
  fi

  if [ -f "$ENV_FILE" ]; then
    docker-compose -f "$PROJECT_DIR/$COMPOSE_FILE" exec app bash
  else
    echo "Environment file $ENV_FILE missing. Aborting."
  fi
fi
