#!/usr/bin/env bash

if [ -z "$PROJECT_DIR" ]; then
  echo "PROJECT_DIR is required."
else
  echo "Running shell within data container..."
  echo ""

  ENV_FILE="$PROJECT_DIR/.env"

  if [ -f "$ENV_FILE" ]; then
    docker-compose -f "$PROJECT_DIR/compose-local.yaml" exec data bash
  else
    echo "Environment file $ENV_FILE missing. Aborting."
  fi
fi
